run:
	./out

run1:
	g++ CacheTime.c -o out -march=native
	./out

run2:
	g++ FlushReload.c -o out -march=native
	./out

run3:
	g++ SpectreExperiment.c -o out -march=native
	./out

run4:
	g++ SpectreAttack.c -o out -march=native
	./out

run5:
	g++ SpectreAttackImproved.c -o out -march=native
	./out


