
run:
	./out

run1:
	g++ CacheTime.cpp -o out -march=native
	./out

run2:
	g++ FlushReload.cpp -o out -march=native
	./out

run3:

run4:
	g++ AccessMemoryKernel.cpp -o out
	./out

run5:
	g++ ExceptionHandling.c -o out -march=native
	./out

run6:
	g++ MeltdownExperiment.c -o out -march=native
	./out

run8:
	g++ MeltdownAttack.c -o out -march=native
	./out
